In [16]:
import numpy as np

a = np.array([1, 2 ,45, 3, 4, 5])

print(a)
print(type(a))

[ 1  2 45  3  4  5]
<class 'numpy.ndarray'>


In [8]:
#DIMENSTION IN ARRY 
# 0 D arry  0- D array are element in arry
a= np.array(15)
print(a)

15


In [24]:
#1 D array an array that has 0 -D 
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [33]:
# 2-D array in that has 1-D array as its elements
a=np.array([[1, 2, 3], [4, 5, 6]])

print(a)


[[1 2 3]
 [4 5 6]]


In [25]:
# 3-D array that has 2-D array element
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [30]:
#check the number of dimenshion Numpy array has provide ndim attribute
a=np.array([1,2,3,4,5])
b=np.array([[1, 2, 3], [4, 5, 6]])
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(a.itemsize)





1
2
3
4


In [ ]:
#

In [46]:
a=np.array([1,2,3,4,5])
b=a
print(a.size)

5
