Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4,5])
print(a[1])


2


In [3]:
# 2 D array indexing
b = np.array([[1,2,3,4],[5,6,7]])
print(b)

[list([1, 2, 3, 4]) list([5, 6, 7])]


<ipython-input-3-ba5d2f36d21c>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[1,2,3,4],[5,6,7]])


In [4]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])



2nd element on 1st dim:  2


In [5]:
# slicing array
#Slicing in python means taking elements from one given index to 
#another given index.
a= np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5])



[2 3 4 5]


In [6]:
#Slice elements from index 4 to the end of the array:
a= np.array([1,2,3,4,5,6,7,8,9,10])
print(a[4:])


[ 5  6  7  8  9 10]


In [7]:
#slicing element from beginig to index 4
a= np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:4])

[1 2 3 4]


In [8]:
#negative slicing
a= np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-9:])
print(a[-4::2])

[ 2  3  4  5  6  7  8  9 10]
[7 9]


In [9]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a[1,1:])

[ 7  8  9 10]
